[tool.poetry]
name = "fastapi3"
version = "0.1.0"
description = ""
authors = ["Mirbryuk <mashamirbryuk@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.108.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
